#
# LEVELS BY THEDACHICKEN
#

# LIST OF STORAGE PLACES
# Options: FILE, MYSQL
StoragePlace: "FILE"
MYSQLOptions:
  Host: localhost
  Port: 3306
  Database: Levels
  Username: root
  Password: password


# THIS OPTION MUST BE THE SAME ON EACH BUNGEECORD SERVER IF USING MYSQL OR THERE WILL BE DIFFERENT MAX POINTS ON EACH SERVER. <--
# Options: Specific, Multiplier
LevelUpType: "SPECIFIC"
# Multiplier: Times from start amount.
# Specific: Give max per level.

Specific:
  # LEVEL: MAX POINTS
  '1': 50
  '2': 110
  '5': 600

Multiplier:
  StartAmount: 60
  MultiplierAmount: 4

LevelPrefix:
  # LEVEL: PREFIX
  '0': "&7&l"
  '19': "&6&l"

# This allows you to enable and run commands when someone leveled up!
# Variables:
# %player% - Player's name
levelupruncommand: false
levelupruncommandslist:
  - "msg %player% wow!"
  - "msg %player% Thanks for downloading Levels!"

#This is for if you want to reward the player with a command per type of level.
levelupruncommandcertainperlevel: false
#^^^ To Enable this "levelupruncommand" needs to be enabled.
#When enabled "levelupruncommandlist" will be ignored.

levelcommands:
  1:
    - "tell %player% thanks!"
  5:
    - "tell %player% wow! Good Job :)"
  10:
    - "tell %player% :>"

Nametag:
  # Hooks into NameTagEdit if installed.
  Enable: false
  # Options: PREFIX, SUFFIX.
  Location: 'PREFIX'
