#
# LEVELS - BY THEDACHICKEN
#

# LIST OF STORAGE PLACES
# Options: FILE, MYSQL
StoragePlace: "FILE"
MYSQLOptions:
  Host: localhost
  Port: 3306
  Database: Levels
  Username: root
  Password: password


# THIS OPTION MUST BE THE SAME ON EACH BUNGEECORD SERVER IF USING MYSQL OR THERE WILL BE DIFFERENT MAX POINTS ON EACH SERVER. <--
# Options: Specific, Multiplier
LevelUpType: "SPECIFIC"
# Multiplier: Times from start amount.
# Specific: Give max per level.

Specific:
  # LEVEL: POINTS
  1: 50
  2: 110
  5: 600

Multiplier:
  StartAmount: 60
  MultiplierAmount: 4

Nametag:
  # Hooks into NameTagEdit if installed.
  Enable: false
  # Options: PREFIX, SUFFIX.
  Location: 'PREFIX'
