#
# LEVELS BY THEDACHICKEN [LIST OF OLD NAMES: https://namemc.com/profile/TheDaChicken.4]
#

# LIST OF STORAGE PLACES
# Options: FILE, MYSQL
StoragePlace: "FILE"
MYSQLOptions:
  Host: localhost
  Port: 3306
  Database: Levels
  Username: root
  Password: password


# THIS OPTION MUST BE THE SAME ON EACH BUNGEECORD SERVER IF USING MYSQL OR THERE WILL BE DIFFERENT MAX POINTS ON EACH SERVER. <--
# Options: Specific, Multiplier
LevelUpType: "SPECIFIC"
# Multiplier: Times from start amount.
# Specific: Give max per level.

Specific:
  # LEVEL: MAX POINTS
  '1': 50
  '2': 110
  '5': 600

Multiplier:
  StartAmount: 60
  MultiplierAmount: 4

LevelPrefix:
  # LEVEL: PREFIX
  '0': "&7&l"
  '19': "&6&l"

LevelUpRunCommand:
  # This allows you to enable and run commands when someone leveled up!
  # Variables:
  # %player% - Player's name
  Enable: false
  list:
    - "msg %player% wow!"
    - "msg %player% Thanks for downloading Levels!"
  certainperLevel: false
  perLevel:
    1:
      - "tell %player% thanks!"
    5:
      - "tell %player% wow! Good Job :)"
    10:
      - "tell %player% :>"

Nametag:
  # Hooks into NameTagEdit if installed.
  Enable: false
  # Options: PREFIX, SUFFIX.
  Location: 'PREFIX'

KillEntities:
  #KillMobsPoints when enabled needs to restart the server to create a config with a file of a list of mobs that you can set points when given when something is killed.
  EnableMobsPoints: false
  # EnableKillMobsPoints, when enabled, gives points to player, when player kills another player.
  EnablePlayerPoints: false
  # Amount of points to give to the a player when kills a player.
  PlayerPointsAmount: 6
