#
# LEVELS - BY THEDACHICKEN
#

# LIST OF STORAGE PLACES
# Options: FILE, MYSQL
StoragePlace: "FILE"
MYSQLOptions:
  Host: localhost
  Port: 3306
  Database: Levels
  Username: root
  Password: password


# Options: Specific, Multiplier
LevelUpType: "SPECIFIC"
# Multiplier: Times from start amount.
# Specific:

Multiplier:
  StartAmount: 60
  MultiplierAmount: 4

Nametag:
  # Hooks into NameTagEdit if installed.
  Enable: false
  # Options: PREFIX, SUFFIX.
  Location: 'PREFIX'
