###################################
#                                 #
#    LEVELS by DatChicken         #
#                                 #
###################################

Force Level Prefix to any chat plugin: true
# This may not work on some Chat Plugins!

#Variables:
#%levelstring% (contains the levelprefix with the levelnumber
#%level% is just the levelnumber.
#%levelprefix% is just the prefix.
ForceChatFormat: " %levelprefix%%level% "

#This allows you to tell the where the plugin data is going to go for
#Options: FILE, MYSQL
STORAGEPlace: "FILE"
MYSQLOptions: #ONLY IF MYSQL IS ON IN THE STORAGE PLACE
  Host: localhost
  Port: 3306
  Database: Levels
  Username: root
  Password: password

EnableLevelOnTopOfHead: false

EnableLevelOnPrefix: true
EnableLevelOnSuffix: false

SupportforNameTagEdit: false
redirectstatstolevelstats: true

#
#This allows you to change the add points message location.
#List of Locations: CHAT, ACTIONBAR (IF SERVER SUPPORTS), CLEAR (NOTHING)
AddPointsMessageLocation: "ACTIONBAR"

#
#This allows you to change the subtract points message location.
#List of Locations: CHAT, ACTIONBAR (IF SERVER SUPPORTS), CLEAR (NOTHING)
SubtractPointsMessageLocation: "ACTIONBAR"

# This allows you to enable and run commands when someone leveled up!
# Variables:
# %player% - Player's name
levelupruncommand: false
levelupruncommandslist:
  - "msg %player% wow!"
  - "msg %player% Thanks for downloading Levels!"

#This is for if you want to reward the player with a command per type of level.
levelupruncommandcertainperlevel: false
#^^^ To Enable this "levelupruncommand" needs to be enabled.
#When enabled "levelupruncommandlist" will be ignored.

levelcommands:
  1:
    - "tell %player% thanks!"
  5:
    - "tell %player% wow! Good Job :)"
  10:
    - "tell %player% :>"

# If you don't want a MaxLevel: Put "no"
# Example how it should look like with a number MaxLevel: "1"
MaxLevel: "no"

#The MaxLevelPrefix is the prefix that will be always set after that level (used when max level is off)
MaxLevelPrefix: 19

LevelColorPrefix:
  0: "&7&l"
  1: "&7&l"
  2: "&7&l"
  3: "&7&l"
  4: "&7&l"
  5: "&7&l"
  6: "&7&l"
  7: "&7&l"
  8: "&7&l"
  9: "&7&l"
  10: "&7&l"
  11: "&6&l"
  12: "&6&l"
  13: "&6&l"
  14: "&6&l"
  15: "&6&l"
  16: "&6&l"
  17: "&6&l"
  18: "&6&l"
  19: "&6&l"

#This is were you put the points until leveling up to the next level!
#If you have max level level on, it will by default set the max level to 0 (without changing the config)

#Same as MaxLevelPrefix but with Points in this file.
MaxLevelPoints: 19

#FORMAT:
#LEVEL: Points

0: 100

1: 200

2: 300

3: 400

4: 500

5: 600

6: 700

7: 800

8: 900

9: 1000

10: 1100

11: 1200

12: 1300

13: 1400

14: 1500

15: 1600

16: 1700

17: 1800

18: 1900

19: 2000


#This allows you (with Vault) to auto add a permission to the user when they level up.
  ##The Permission allows you to check if the player has level up to that level.
  ##This could be great to the plugins that you only want players to access if you level up to the level!
  ##Permission Format: levels.level.<level number>
LevelUpPermission: false
#Make sure you have Vault Installed or this will not work!

# Stuff you can get points for!

#Block Break gives points when a person is breaking a blocks! It not recommended, to do this since someone can abuse this by just using swords and trying to break a block.
BlockBreaking: false
#RandomBreakingRandom will give random points from a range!
BlockBreakingRandom: true

#This is just for regular block Breaking:
BlockBreakingPoints: 1

#Random Block Breaking Range:

BlockBreakingMin: 0
BlockBreakingMax: 1

# You can't use decimals. Just so you know.


#KillMobsPoints when enabled needs to restart the server to create a config with a file of a list of mobs that you can set points when given when something is killed.
EnableKillMobsPoints: false

Leaderboard:
  #This Enables Level Leaderboard Command! To Fully setup this do /ll
  Enable: true

  #This allows you to change the command.
  LevelboardCommand: "/leaderboard"

  LowestLeaderboardPosition: 10

  #This allows you to change the message that is on the leaderboards!
  LeaderboardMessage: "%positionprefix%&r. %player_name%: %level_number%"

  #This allows you to change the color/prefix under the positions on the leaderboard. Make sure your have a prefix from top to the lowest leaderboard position.
  PositionPrefix:
    1: "&c&l1"
    2: "&a&l2"
    3: "&a&l3"
    4: "&9&l4"
    5: "&9&l5"
    6: "&1&l6"
    7: "&1&l7"
    8: "&1&l8"
    9: "&8&l9"
    10: "&7&l10"

  #%positionprefix% not supported (right now)
  LeaderHead:
    SignMessage:
      - "&a&lPosition: %position%"
      - "&a&l%player_name%"
      - "&a&lLevel: %level_number%"
    SignMessageNoOneThere:
      - "&a&lPosition: %position%"
      - "&c&lNo Player"
      - "&c&lNULL"