name: Levels
main: level.plugin.Main
version: 4
author: TheDaChicken
softdepend: [PlaceholderAPI,HolographicDisplays,Vault]
commands:
  levelstats:
    aliases: [ls]
    description: Shows players stats level's stats and yours!
  changelevel:
    aliases: [cl, setlevel, changlevel]
    description: Changes player's level!
  addPoints:
    aliases: [ap]
    description: Add points to a player!
  changepoints:
    aliases: [cp]
    description: Change Poi nts of a player.
  addlevel:
    aliases: [al]
    description: Adds to the player's level.